### ISSUE TITLE
Add code for the TODO: fetch all contacts

### ISSUE THREAD

**Issue by decagondev** [HoylakeComputerClub/react-contact-app-fe#1]
## use fetch api to update the code inside the `useEffect` inside the `ContactList.jsx` file to do a get request and then use the `setContacts` hook to update the state with the new data. 
- the fetch needs to be tested locally on the backend so you will need to clone the backend first
- the backend will expose the contacts at the address `http://localhost:3000/contacts`
- read the [CONTRIBUTION](CONTRIBUTION.md) file for details of where to get the backend
please feel free to ask questions as a comment of this Issue.

**Comment by hakikat011** [comment]
hi @decagondev i would love to take on this issue and work on it , could you please assign it to me

**Comment by Yash282003** [comment]
@decagondev I would like to work on this issue. Can you please assign it to me?

**Comment by decagondev** [comment]
@hakikat011 I have assignt the issue to you as you were the first to ask :+1: 
@Yash282003  I will make some more Issues and be assigning people on a first come first assign basis :+1:
