### ISSUE TITLE
Add functionality to the AddContact.jsx form

### ISSUE THREAD

**Issue by decagondev** [HoylakeComputerClub/react-contact-app-fe#3]
## Inside the `AddContact.jsx` form add a `handleAddContact` function
remember to add some imports for `useState` and `useNavigate`

- add a fetch API post request to the local back-end after setting up the back-end locally (`http://localhost:3000/contacts`)
- make sure to navigate to `/` after a successful post of a new contact

**See the [CONTRIBUTING](https://github.com/HoylakeComputerClub/react-contact-app-fe/blob/main/CONTRIBUTING.md) file for details about the back-end repository**

for any further details please feel free to leave a comment.

**Comment by hakikat011** [comment]
hi sir @decagondev , thank you for assigning me on your previous issue , I would love to work on this raised issue as well .

**Comment by decagondev** [comment]
@hakikat011 I have assigned this to you :+1:
