### ISSUE TITLE
Add the logic for EditContact.jsx

### ISSUE THREAD

**Issue by decagondev** [HoylakeComputerClub/react-contact-app-fe#5]
# This one is to add the logic to edit a contact
- set up the backend from the  [Backend Repository](https://github.com/HoylakeComputerClub/contact-app-be)
- import useEffect and useState hooks
- import useParams and useNavigate hooks
- add a useEffect to load in a contact by id (you might want to useParams to get the id
- add a handleEditContact function using fetch API
- add a form to edit the contact data similar to the AddContact.jsx form

**This should make for a fairly straight forward issue. if there are any questions please feel free to leave a comment.**

**Comment by VishalMyla** [comment]
Can I work on this issue ?

**Comment by Ritish134** [comment]
Hi there excited to contribute can you please assign me.

**Comment by decagondev** [comment]
@VishalMyla I will assign you to this as you were the first to ask. @Ritish134  I will be making more issues to be worked on and it is usually first to ask gets assigned

**Comment by hakikat011** [comment]
hi @decagondev , I would love to work on this , i see you have assigned it to another student but can i still work on it and try to contribute?

**Comment by VishalMyla** [comment]
Please review the PR : [5](https://github.com/HoylakeComputerClub/react-contact-app-fe/pull/7)

**Comment by decagondev** [comment]
Thanks @VishalMyla  I have taken a look at your PR and it fits the specification well and is clean. I have merged it :+1:
